# Generated by Django 3.2.8 on 2021-11-08 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, unique=True, verbose_name='Uquvchini FIO')),
                ('contc', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('id_cart_seria', models.CharField(max_length=2, unique=True, verbose_name='Pasport seriasi')),
                ('id_cart_num', models.BigIntegerField(max_length=7, unique=True, verbose_name='Pasport seriasi')),
                ('address', models.CharField(max_length=100, verbose_name='Adresini kititing')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Parol')),
            ],
            options={
                'verbose_name': 'Uquvchi',
                'verbose_name_plural': '#5 Uquvchilar',
            },
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('dic', models.TextField(verbose_name='Kurs xaqida')),
                ('prise', models.BigIntegerField(max_length=6, verbose_name='Kurs narxi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': '#2 Kurslar',
            },
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='Grupani nomi')),
                ('group_start', models.DateTimeField(help_text='Ota-onalar bilishi uchun', verbose_name='Grupa darsga kelish vaqti')),
                ('group_end', models.DateTimeField(verbose_name='Grupa darsdan ketishi')),
                ('courses_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.courses', verbose_name='Qaysi kursni grupasi')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': '#3 Grupalar',
            },
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(choices=[('tashkent', 'Toshkent'), ('karklp', 'Qoraqalpog’iston Respublikasi'), ('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qarsh', 'Qashqadaryo viloyati'), ('navoi', 'Navoiy viloyati'), ('namagan', 'Namangan viloyati'), ('samarkand', 'Samarqand viloyati'), ('surxandar', 'Surxondaryo viloyati'), ('sirdar', 'Sirdaryo viloyati'), ('tash_obl', 'Toshkent viloyati'), ('fergana', 'Farg’ona viloyati'), ('xorezm', 'Xorazm viloyati')], max_length=255, verbose_name='Viloyatni tanglang')),
            ],
            options={
                'verbose_name': 'Vilayat',
                'verbose_name_plural': '#0 Vilayatlar',
            },
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savolni kriting')),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('true', models.IntegerField(verbose_name='Tugri javobni IDsini kiting')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduApp.groups', verbose_name='Qaysi grupani testi')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': '#9 Testlar',
            },
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_fio', models.CharField(max_length=255, unique=True, verbose_name='FIO')),
                ('skill', models.CharField(max_length=255, verbose_name='Qobiliyati')),
                ('mobile', models.CharField(max_length=13, unique=True, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('linkedin', models.CharField(blank=True, max_length=255, verbose_name='Linkedin')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='Github ')),
                ('groups_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.groups', verbose_name='Qaysi kursni ustozi')),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': '#4 Ustozlar',
            },
        ),
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='Uquv markaz moni')),
                ('address', models.CharField(max_length=100, verbose_name='Adresini kititing')),
                ('director', models.CharField(max_length=100, verbose_name='Direktor FIO :')),
                ('longitude', models.CharField(blank=True, max_length=255, verbose_name='Geologicheskiy uzunlik')),
                ('latitude', models.CharField(blank=True, max_length=255, verbose_name='Geologicheskiy kenglik')),
                ('region_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.regions', verbose_name='Viloyatni tanglang')),
            ],
            options={
                'verbose_name': 'Uquv markaz',
                'verbose_name_plural': '#1 Uquv markazlar',
            },
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Otasini FIO')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=100, verbose_name='Adresini kititing')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Parol')),
                ('clients_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.clients', verbose_name='Kimni ota-onasi')),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': '#6 Ota-onalar',
            },
        ),
        migrations.CreateModel(
            name='lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les_theme', models.CharField(max_length=100, verbose_name='Dars mavzusi')),
                ('les_date', models.DateField(default=datetime.datetime.today, verbose_name='Dars kuni')),
                ('les_start', models.TimeField(verbose_name='Dars boshlanish vaqti')),
                ('les_end', models.TimeField(verbose_name='Dars tugashi vaqti')),
                ('groups_les_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.groups', verbose_name='Qaysi grupaga dars buladi')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': '#7 Darslar',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='school_name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.schools', verbose_name='Uquv markaz nomi'),
        ),
        migrations.AddField(
            model_name='clients',
            name='groups_clients_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.groups', verbose_name='Qaysi kursni uquvchisi'),
        ),
        migrations.CreateModel(
            name='attentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_atten', models.DateField(default=datetime.datetime.today, verbose_name='Dars kuni')),
                ('clients_atten_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.clients', verbose_name='Uquvchi ismi')),
                ('lesson_atten_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.lessons', verbose_name='Qaysi dars')),
            ],
            options={
                'verbose_name': 'Monitoring',
                'verbose_name_plural': '#8 Monitoringlar',
            },
        ),
    ]
